# Generated by Django 5.0.7 on 2024-09-29 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='about_us_images/')),
                ('motto', models.CharField(max_length=255)),
                ('company_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_name', models.CharField(max_length=255)),
                ('digital_address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('logo', models.ImageField(upload_to='company_logos/')),
            ],
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_name', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='OpeningHoursType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('base_type', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('warranty_duration', models.CharField(blank=True, max_length=100, null=True)),
                ('model_number', models.CharField(blank=True, max_length=100, null=True)),
                ('output_power', models.CharField(blank=True, max_length=100, null=True)),
                ('power_factor', models.CharField(blank=True, max_length=100, null=True)),
                ('output_voltage', models.CharField(blank=True, max_length=100, null=True)),
                ('output_current', models.CharField(blank=True, max_length=100, null=True)),
                ('normal_frequency', models.CharField(blank=True, max_length=100, null=True)),
                ('rated_speed', models.CharField(blank=True, max_length=100, null=True)),
                ('diesel_oil_type', models.CharField(blank=True, max_length=100, null=True)),
                ('steady_state_voltage_regulation_rate', models.CharField(blank=True, max_length=100, null=True)),
                ('voltage_fluctuation_rate', models.CharField(blank=True, max_length=100, null=True)),
                ('transient_voltage_regulation', models.CharField(blank=True, max_length=100, null=True)),
                ('voltage_settling_time', models.CharField(blank=True, max_length=100, null=True)),
                ('steady_state_frequency_control', models.CharField(blank=True, max_length=100, null=True)),
                ('frequency_jitter', models.CharField(blank=True, max_length=100, null=True)),
                ('transient_frequency_fluctuation', models.CharField(blank=True, max_length=100, null=True)),
                ('frequency_stabilization_time', models.CharField(blank=True, max_length=100, null=True)),
                ('fuel_consumption_mcr', models.CharField(blank=True, max_length=100, null=True)),
                ('noise_lp7m', models.CharField(blank=True, max_length=100, null=True)),
                ('diesel_engine_brand_provenance', models.CharField(blank=True, max_length=100, null=True)),
                ('diesel_engine_model_number', models.CharField(blank=True, max_length=100, null=True)),
                ('stand_by_power', models.CharField(blank=True, max_length=100, null=True)),
                ('cylinder_model_type', models.CharField(blank=True, max_length=100, null=True)),
                ('bore_stroke', models.CharField(blank=True, max_length=100, null=True)),
                ('compression_ratio', models.CharField(blank=True, max_length=100, null=True)),
                ('starting_system', models.CharField(blank=True, max_length=100, null=True)),
                ('cooling_system', models.CharField(blank=True, max_length=100, null=True)),
                ('fuel_system', models.CharField(blank=True, max_length=100, null=True)),
                ('speed_regulating_system', models.CharField(blank=True, max_length=100, null=True)),
                ('air_intake_method', models.CharField(blank=True, max_length=100, null=True)),
                ('displacement', models.CharField(blank=True, max_length=100, null=True)),
                ('engine_oil_capacity', models.CharField(blank=True, max_length=100, null=True)),
                ('rotation_rate', models.CharField(blank=True, max_length=100, null=True)),
                ('alternator_brand_place_of_origin', models.CharField(blank=True, max_length=100, null=True)),
                ('motor_type', models.CharField(blank=True, max_length=100, null=True)),
                ('rated_power', models.CharField(blank=True, max_length=100, null=True)),
                ('rated_voltage', models.CharField(blank=True, max_length=100, null=True)),
                ('insulation_grade', models.CharField(blank=True, max_length=100, null=True)),
                ('protection_degree', models.CharField(blank=True, max_length=100, null=True)),
                ('connection_mode', models.CharField(blank=True, max_length=100, null=True)),
                ('adjustment_mode', models.CharField(blank=True, max_length=100, null=True)),
                ('output_frequency', models.CharField(blank=True, max_length=100, null=True)),
                ('output_factor', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(choices=[('rental', 'Rental'), ('sale', 'Sale')], max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='OpeningHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.CharField(max_length=100)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drape_app.openinghourstype')),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('effective_date', models.DateField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='drape_app.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='drape_app.producttype'),
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('services', models.CharField(choices=[('Diagnostic Test', 'Diagnostic Test'), ('Engine Servicing', 'Engine Servicing'), ('Tires Replacement', 'Tires Replacement'), ('Oil Changing', 'Oil Changing')], max_length=50)),
                ('start_date', models.DateTimeField()),
                ('due_date', models.DateTimeField()),
                ('message', models.TextField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drape_app.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('operations', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='service_images/')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drape_app.servicetype')),
            ],
        ),
    ]
