# Generated by Django 5.0.7 on 2024-10-27 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drape_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttype',
            name='type_name',
            field=models.CharField(choices=[('Rental', 'Rental'), ('Sale', 'Sale')], max_length=10, unique=True),
        ),
    ]
