# Generated by Django 5.0.4 on 2024-08-02 07:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drape_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media/about_us_files/'),
        ),
        migrations.AlterField(
            model_name='analytics',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media/analytics_files/'),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(upload_to='media/company_logos/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media/product_files/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media/service_files/'),
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('services', models.CharField(choices=[('MAINTENANCE', 'Maintenance'), ('SERVICE2', 'Service 2'), ('SERVICE3', 'Service 3'), ('SERVICE4', 'Service 4')], max_length=50)),
                ('start_date', models.DateTimeField()),
                ('due_date', models.DateTimeField()),
                ('message', models.TextField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drape_app.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
