# Generated by Django 5.0.7 on 2024-10-06 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drape_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookForService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_name', models.CharField(max_length=100)),
                ('email_address', models.EmailField(max_length=254)),
                ('service_date', models.DateTimeField()),
                ('special_request', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='contactus',
            name='subject',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
