# Generated by Django 5.0.7 on 2024-10-06 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drape_app', '0002_bookforservice_alter_contactus_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookforservice',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
