# Generated by Django 5.0.7 on 2024-10-28 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drape_app', '0002_alter_producttype_type_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminpostnewsletter',
            name='attachments',
        ),
        migrations.DeleteModel(
            name='Attachment',
        ),
    ]
