# Generated by Django 5.0.7 on 2024-10-06 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drape_app', '0003_bookforservice_is_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookforservice',
            name='services',
            field=models.CharField(choices=[('Diagnostic Test', 'Diagnostic Test'), ('Engine Servicing', 'Engine Servicing'), ('Tires Replacement', 'Tires Replacement'), ('Oil Changing', 'Oil Changing')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
