# Generated by Django 5.0.7 on 2024-08-19 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drape_app', '0003_alter_schedule_services'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analytics',
            name='file',
        ),
    ]
