# Generated by Django 5.0.7 on 2024-08-19 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drape_app', '0004_remove_analytics_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutus',
            old_name='motor',
            new_name='motto',
        ),
    ]
