# Generated by Django 5.0.7 on 2024-10-27 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drape_app', '0005_newsletter_technicalteammember_aboutus_about_us_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company',
        ),
    ]
