# Generated by Django 5.0.7 on 2024-08-19 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drape_app', '0005_rename_motor_aboutus_motto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutus',
            name='file',
        ),
        migrations.RemoveField(
            model_name='product',
            name='file',
        ),
        migrations.AddField(
            model_name='aboutus',
            name='image',
            field=models.ImageField(default='image', upload_to='media/about_us_images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/product_images/'),
        ),
    ]
