# Generated by Django 5.0.7 on 2024-08-19 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drape_app', '0006_remove_aboutus_file_remove_product_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='file',
        ),
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/service_images/'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='about_us_images/'),
        ),
    ]
