# Generated by Django 5.0.7 on 2024-09-29 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drape_app', '0009_producttype_price_product_product_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='specification',
        ),
    ]
